### ISSUE TITLE
首页第一次进入没有内容显示

### ISSUE THREAD

**Issue by Clearlee** [xiaohaibin/OpenEyes#8]
09-05 20:54:27.254 18904-19004/com.stx.openeyes E/Volley: [71628] NetworkDispatcher.run: Unhandled exception java.lang.RuntimeException: Bad URL null
                                                          java.lang.RuntimeException: Bad URL null
                                                              at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:151)
                                                              at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
                                                           Caused by: java.net.MalformedURLException
                                                              at java.net.URL.<init>(URL.java:152)
                                                              at java.net.URL.<init>(URL.java:125)
                                                              at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
                                                              at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97)
                                                              at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114) 
请问这是什么原因呢？

**Comment by xiaohaibin** [comment]
感谢提出问题，已修正，稍后更新代码

**Comment by Clearlee** [comment]
第一次进入，执行downLoad(HttpAdress.DAILY)会报这个错。
但是下拉刷新一次，同样执行downLoad(HttpAdress.DAILY)，内容就出来了。
是Volley的原因还是其他原因呢？
我尝试在onErrorResponse方法里再次downLoad一次，问题就解决了，但是感觉治标不治本，而且会存在新的问题。

**Comment by xiaohaibin** [comment]
这个属于Volley的问题，我采用okhttp加载网络数据即可

**Comment by xiaohaibin** [comment]
代码已更新，可更新下载看下

**Comment by xsjqqq123** [comment]
@xiaohaibin 还是一样哦，不更新
