### ISSUE TITLE
进入播放时崩溃

### ISSUE THREAD

**Issue by xsjqqq123** [xiaohaibin/OpenEyes#9]
提示如下：
-classes.dex"],nativeLibraryDirectories=[/data/app/com.stx.openeyes-1/lib/arm64, /system/fake-libs64, /data/app/com.stx.openeyes-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libvinit.so"
                                                                      at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                      at java.lang.System.loadLibrary(System.java:1530)
                                                                      at io.vov.vitamio.Vitamio.<clinit>(Vitamio.java:258)
                                                                      at com.stx.openeyes.view.activity.ShowVideoActivity.onCreate(ShowVideoActivity.java:43)

引入了aar，删除了你这个目录下的vitamio.（自带的这个也是同样崩溃），手机小米5

**Comment by xiaohaibin** [comment]
6.0的系统么

**Comment by xsjqqq123** [comment]
小米5已经是7.0系统了

**Comment by chenzhen1994** [comment]
android 6.0无法打开app

**Comment by chenzhen1994** [comment]
android 6.0无法播放

**Comment by xiaohaibin** [comment]
换个视频播放框架即可

**Comment by xiaohaibin** [comment]
更新了代码
